#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT_DIR"

: "${HEX_CACHE_RESERVE_STATES:=2000000}"
: "${HEX_PROGRESS_INTERVAL_STATES:=10000}"
: "${HEX_SEED_TIME_LIMIT_SECONDS:=20}"
: "${HEX_LOCAL_CANDIDATE_BUDGET:=128}"
: "${HEX_RETRY_EXHAUSTED_SWEEPS:=0}"
: "${HEX_RUN_TIMEOUT_SECONDS:=0}"

make

echo "Running hex with:"
echo "  HEX_CACHE_RESERVE_STATES=$HEX_CACHE_RESERVE_STATES"
echo "  HEX_PROGRESS_INTERVAL_STATES=$HEX_PROGRESS_INTERVAL_STATES"
echo "  HEX_SEED_TIME_LIMIT_SECONDS=$HEX_SEED_TIME_LIMIT_SECONDS"
echo "  HEX_LOCAL_CANDIDATE_BUDGET=$HEX_LOCAL_CANDIDATE_BUDGET"
echo "  HEX_RETRY_EXHAUSTED_SWEEPS=$HEX_RETRY_EXHAUSTED_SWEEPS"

if [[ "$HEX_RUN_TIMEOUT_SECONDS" -gt 0 ]]; then
  echo "  timeout=${HEX_RUN_TIMEOUT_SECONDS}s"
  timeout "${HEX_RUN_TIMEOUT_SECONDS}s" \
    env HEX_CACHE_RESERVE_STATES="$HEX_CACHE_RESERVE_STATES" \
        HEX_PROGRESS_INTERVAL_STATES="$HEX_PROGRESS_INTERVAL_STATES" \
        HEX_SEED_TIME_LIMIT_SECONDS="$HEX_SEED_TIME_LIMIT_SECONDS" \
        HEX_LOCAL_CANDIDATE_BUDGET="$HEX_LOCAL_CANDIDATE_BUDGET" \
        HEX_RETRY_EXHAUSTED_SWEEPS="$HEX_RETRY_EXHAUSTED_SWEEPS" \
        ./hex
else
  env HEX_CACHE_RESERVE_STATES="$HEX_CACHE_RESERVE_STATES" \
      HEX_PROGRESS_INTERVAL_STATES="$HEX_PROGRESS_INTERVAL_STATES" \
      HEX_SEED_TIME_LIMIT_SECONDS="$HEX_SEED_TIME_LIMIT_SECONDS" \
      HEX_LOCAL_CANDIDATE_BUDGET="$HEX_LOCAL_CANDIDATE_BUDGET" \
      HEX_RETRY_EXHAUSTED_SWEEPS="$HEX_RETRY_EXHAUSTED_SWEEPS" \
      ./hex
fi
