#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT_DIR"

: "${HEX_CACHE_RESERVE_STATES:=2000000}"
: "${HEX_PROGRESS_INTERVAL_STATES:=20000}"
: "${HEX_SEED_TIME_LIMIT_SECONDS:=0}"
: "${HEX_MAX_DEPTH:=2}"
: "${HEX_EXHAUSTIVE_SEED_LIMIT:=0}"
: "${HEX_RUN_TIMEOUT_SECONDS:=0}"

make

echo "Running hex with:"
echo "  HEX_CACHE_RESERVE_STATES=$HEX_CACHE_RESERVE_STATES"
echo "  HEX_PROGRESS_INTERVAL_STATES=$HEX_PROGRESS_INTERVAL_STATES"
echo "  HEX_SEED_TIME_LIMIT_SECONDS=$HEX_SEED_TIME_LIMIT_SECONDS"
echo "  HEX_MAX_DEPTH=$HEX_MAX_DEPTH"
echo "  HEX_EXHAUSTIVE_SEED_LIMIT=$HEX_EXHAUSTIVE_SEED_LIMIT"

if [[ "$HEX_RUN_TIMEOUT_SECONDS" -gt 0 ]]; then
  echo "  timeout=${HEX_RUN_TIMEOUT_SECONDS}s"
  timeout "${HEX_RUN_TIMEOUT_SECONDS}s" \
    env HEX_CACHE_RESERVE_STATES="$HEX_CACHE_RESERVE_STATES" \
        HEX_PROGRESS_INTERVAL_STATES="$HEX_PROGRESS_INTERVAL_STATES" \
        HEX_SEED_TIME_LIMIT_SECONDS="$HEX_SEED_TIME_LIMIT_SECONDS" \
        HEX_MAX_DEPTH="$HEX_MAX_DEPTH" \
        HEX_EXHAUSTIVE_SEED_LIMIT="$HEX_EXHAUSTIVE_SEED_LIMIT" \
        ./hex
else
  env HEX_CACHE_RESERVE_STATES="$HEX_CACHE_RESERVE_STATES" \
      HEX_PROGRESS_INTERVAL_STATES="$HEX_PROGRESS_INTERVAL_STATES" \
      HEX_SEED_TIME_LIMIT_SECONDS="$HEX_SEED_TIME_LIMIT_SECONDS" \
      HEX_MAX_DEPTH="$HEX_MAX_DEPTH" \
      HEX_EXHAUSTIVE_SEED_LIMIT="$HEX_EXHAUSTIVE_SEED_LIMIT" \
      ./hex
fi
